## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# List here the tasks and the commands for this workflow
# then run `fzz` to start to work.

- name: tests
  run: 
    - make test
    - make lint
    - make format
    - "git add {{relative_path}}"
  change: '**/*.py'
  ignore: 
    - "*.pyc"
    - "**/venv/**"
    - "**/__pycache__/**"
    - "**/.tox/**"
    
